import { NextRequest } from 'next/server';
import { createHandler, successResponse } from '@/lib/api/utils/handler';

// Mock data for Atlanta rentals
const atlantaRentals = [
  {
    id: '1',
    property_type: 'Apartment',
    street_address: '123 Peachtree St',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30308',
    neighborhood: 'Midtown',
    monthly_rent: 1800,
    security_deposit: 1800,
    utilities: ['Water', 'Trash'],
    utilities_cost: 100,
    bedrooms: 1,
    bathrooms: 1,
    square_feet: 750,
    parking: true,
    parking_fee: 100,
    pet_friendly: true,
    pet_deposit: 250,
    amenities: ['Pool', 'Gym', 'Furnished'],
    minimum_lease: 12,
    available_date: '2025-04-01',
    application_fee: 50,
    property_management: 'Atlanta Property Group',
    contact_phone: '404-555-1234',
    contact_email: 'info@apg.com',
    latitude: 33.7748,
    longitude: -84.3655,
    nearby_transportation: ['MARTA Station', 'Bus Stop'],
    created_at: '2025-03-15T12:00:00Z',
    user_id: null
  },
  {
    id: '2',
    property_type: 'House',
    street_address: '456 Piedmont Ave',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30309',
    neighborhood: 'Ansley Park',
    monthly_rent: 3200,
    security_deposit: 3200,
    utilities: ['Gas'],
    utilities_cost: 150,
    bedrooms: 3,
    bathrooms: 2.5,
    square_feet: 1800,
    parking: true,
    parking_fee: 0,
    pet_friendly: true,
    pet_deposit: 300,
    amenities: ['Backyard', 'Fireplace'],
    minimum_lease: 12,
    available_date: '2025-04-15',
    application_fee: 75,
    property_management: 'Atlanta Homes',
    contact_phone: '404-555-5678',
    contact_email: 'rentals@atlantahomes.com',
    latitude: 33.7915,
    longitude: -84.3766,
    nearby_transportation: ['Bus Stop'],
    created_at: '2025-03-18T15:30:00Z',
    user_id: null
  },
  {
    id: '3',
    property_type: 'Condo',
    street_address: '789 10th St NE',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30309',
    neighborhood: 'Midtown',
    monthly_rent: 2200,
    security_deposit: 2200,
    utilities: ['Internet', 'Cable'],
    utilities_cost: 120,
    bedrooms: 2,
    bathrooms: 2,
    square_feet: 1100,
    parking: true,
    parking_fee: 150,
    pet_friendly: false,
    pet_deposit: 0,
    amenities: ['Rooftop Pool', 'Concierge', 'Gym'],
    minimum_lease: 12,
    available_date: '2025-05-01',
    application_fee: 65,
    property_management: 'Midtown Living',
    contact_phone: '404-555-9012',
    contact_email: 'leasing@midtownliving.com',
    latitude: 33.7811,
    longitude: -84.3880,
    nearby_transportation: ['MARTA Station', 'Bike Share'],
    created_at: '2025-03-20T09:15:00Z',
    user_id: null
  },
  {
    id: '4',
    property_type: 'Townhouse',
    street_address: '101 Ponce de Leon Ave',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30308',
    neighborhood: 'Old Fourth Ward',
    monthly_rent: 2800,
    security_deposit: 2800,
    utilities: [],
    utilities_cost: 0,
    bedrooms: 3,
    bathrooms: 2.5,
    square_feet: 1600,
    parking: true,
    parking_fee: 0,
    pet_friendly: true,
    pet_deposit: 300,
    amenities: ['Private Patio', 'Washer/Dryer'],
    minimum_lease: 12,
    available_date: '2025-04-10',
    application_fee: 70,
    property_management: 'Atlanta Urban Living',
    contact_phone: '404-555-3456',
    contact_email: 'info@aul.com',
    latitude: 33.7728,
    longitude: -84.3734,
    nearby_transportation: ['Bus Stop', 'BeltLine Access'],
    created_at: '2025-03-16T14:45:00Z',
    user_id: null
  },
  {
    id: '5',
    property_type: 'Apartment',
    street_address: '222 14th St NE',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30309',
    neighborhood: 'Midtown',
    monthly_rent: 1950,
    security_deposit: 1950,
    utilities: ['Water'],
    utilities_cost: 50,
    bedrooms: 1,
    bathrooms: 1,
    square_feet: 800,
    parking: true,
    parking_fee: 125,
    pet_friendly: true,
    pet_deposit: 250,
    amenities: ['Pool', 'Fitness Center', 'Dog Park'],
    minimum_lease: 12,
    available_date: '2025-05-15',
    application_fee: 55,
    property_management: 'Midtown Properties',
    contact_phone: '404-555-7890',
    contact_email: 'leasing@midtownproperties.com',
    latitude: 33.7863,
    longitude: -84.3824,
    nearby_transportation: ['MARTA Station', 'Bike Share'],
    created_at: '2025-03-19T11:30:00Z',
    user_id: null
  },
  {
    id: '6',
    property_type: 'Apartment',
    street_address: '333 Highland Ave NE',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30312',
    neighborhood: 'Old Fourth Ward',
    monthly_rent: 1650,
    security_deposit: 1650,
    utilities: ['Water', 'Trash'],
    utilities_cost: 80,
    bedrooms: 1,
    bathrooms: 1,
    square_feet: 700,
    parking: true,
    parking_fee: 50,
    pet_friendly: true,
    pet_deposit: 200,
    amenities: ['Furnished', 'Courtyard'],
    minimum_lease: 6,
    available_date: '2025-04-01',
    application_fee: 50,
    property_management: 'Urban Dwellings',
    contact_phone: '404-555-2345',
    contact_email: 'leasing@urbandwellings.com',
    latitude: 33.7615,
    longitude: -84.3662,
    nearby_transportation: ['Bus Stop', 'BeltLine Access'],
    created_at: '2025-03-17T10:00:00Z',
    user_id: null
  }
];

export const GET = createHandler(async (request: NextRequest) => {
  const { searchParams } = new URL(request.url);

  // Extract filters from query parameters
  const minPrice = Number(searchParams.get('minPrice') || 0);
  const maxPrice = Number(searchParams.get('maxPrice') || 10000);
  const minBeds = Number(searchParams.get('minBeds') || 0);
  const minBaths = Number(searchParams.get('minBaths') || 0);
  const petFriendly = searchParams.get('petFriendly') === 'true';

  // Apply filters to the mock data
  const filteredRentals = atlantaRentals.filter(rental => {
    const priceMatch = rental.monthly_rent >= minPrice && rental.monthly_rent <= maxPrice;
    const bedsMatch = rental.bedrooms >= minBeds;
    const bathsMatch = rental.bathrooms >= minBaths;
    const petMatch = !petFriendly || rental.pet_friendly === true;

    return priceMatch && bedsMatch && bathsMatch && petMatch;
  });

  return successResponse(filteredRentals);
});
